# 01 Data Understanding

This notebook explores the airport security checkpoint dataset and identifies the columns, data types, missing values, and possible features for the machine learning project.

In [14]:
import pandas as pd
import numpy as np

Loading the dataset.

In [15]:
file_path = "../data/raw/security_checkpoint_data.xlsx"
all_sheets = pd.read_excel(file_path, sheet_name=None)

dfs = []

for sheet_name, sheet_df in all_sheets.items():
    sheet_df["source_sheet"] = sheet_name
    dfs.append(sheet_df)

df = pd.concat(dfs, ignore_index=True)

print("Combined shape:", df.shape)
df.head()

Combined shape: (2405, 26)

,Comments,Lane number,Date,business,senior,family,young,PRM,regular,Experience,...,Time Start WTMD check,Time End WTMD check,Time Start ETD check,Time End ETD check,Time Start Baggage reclaim,Time End Baggage reclaim,Group size,Time Start Baggage Check,Time End Baggage Check,source_sheet
0,"2x wtmd, shoes",3,2018-02-23 00:00:00,NaN,NaN,NaN,NaN,NaN,1.0,0.0,...,NaN,NaN,NaN,NaN,50552.0,50732.0,2.0,NaN,NaN,2018_02_23
1,NaN,3,2018-02-23 00:00:00,NaN,NaN,NaN,NaN,NaN,1.0,0.0,...,NaN,NaN,50601.0,50608.0,50610.0,50753.0,2.0,NaN,NaN,2018_02_23
2,NaN,3,2018-02-23 00:00:00,NaN,NaN,NaN,NaN,NaN,1.0,0.0,...,NaN,NaN,NaN,NaN,50735.0,50814.0,2.0,NaN,NaN,2018_02_23
3,2x wtmd,3,2018-02-23 00:00:00,NaN,NaN,NaN,NaN,NaN,1.0,0.0,...,NaN,NaN,50741.0,50748.0,50758.0,50859.0,2.0,NaN,NaN,2018_02_23
4,NaN,3,2018-02-23 00:00:00,1.0,NaN,NaN,NaN,NaN,1.0,1.0,...,NaN,NaN,NaN,NaN,51115.0,51213.0,1.0,NaN,NaN,2018_02_23

Previewing the data.

In [16]:
print("Rows, columns:", df.shape)

Rows, columns: (2405, 26)

In [17]:
df.columns.tolist()

['Comments',
 'Lane number',
 'Date',
 'business',
 'senior',
 'family',
 'young',
 'PRM',
 'regular',
 'Experience',
 'Time Start Baggage drop off',
 'Number of boxes',
 'Time End Baggage drop off',
 'Time Start WTMD',
 'Time Start WTMD 2',
 'Time Start WTMD 3',
 'Time Start WTMD check',
 'Time End WTMD check',
 'Time Start ETD check',
 'Time End ETD check',
 'Time Start Baggage reclaim',
 'Time End Baggage reclaim',
 'Group size',
 'Time Start Baggage Check',
 'Time End Baggage Check',
 'source_sheet']

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2405 entries, 0 to 2404
Data columns (total 26 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Comments                     1096 non-null   str
 1   Lane number                  2405 non-null   int64
 2   Date                         2405 non-null   object
 3   business                     444 non-null    float64
 4   senior                       530 non-null    float64
 5   family                       239 non-null    float64
 6   young                        372 non-null    float64
 7   PRM                          25 non-null     float64
 8   regular                      1067 non-null   float64
 9   Experience                   2403 non-null   float64
 10  Time Start Baggage drop off  2404 non-null   float64
 11  Number of boxes              2403 non-null   float64
 12  Time End Baggage drop off    2404 non-null   float64
 13  Time Start WTMD              2400 non-null   float64
 14  Time Start WTMD 2            333 non-null    float64
 15  Time Start WTMD 3            3 non-null      float64
 16  Time Start WTMD check        214 non-null    float64
 17  Time End WTMD check          213 non-null    float64
 18  Time Start ETD check         313 non-null    float64
 19  Time End ETD check           309 non-null    float64
 20  Time Start Baggage reclaim   2396 non-null   object
 21  Time End Baggage reclaim     2396 non-null   float64
 22  Group size                   2402 non-null   float64
 23  Time Start Baggage Check     174 non-null    float64
 24  Time End Baggage Check       169 non-null    float64
 25  source_sheet                 2405 non-null   str
dtypes: float64(21), int64(1), object(2), str(2)
memory usage: 488.6+ KB

In [19]:
df.isnull().sum()

Comments                       1309
Lane number                       0
Date                              0
business                       1961
senior                         1875
family                         2166
young                          2033
PRM                            2380
regular                        1338
Experience                        2
Time Start Baggage drop off       1
Number of boxes                   2
Time End Baggage drop off         1
Time Start WTMD                   5
Time Start WTMD 2              2072
Time Start WTMD 3              2402
Time Start WTMD check          2191
Time End WTMD check            2192
Time Start ETD check           2092
Time End ETD check             2096
Time Start Baggage reclaim        9
Time End Baggage reclaim          9
Group size                        3
Time Start Baggage Check       2231
Time End Baggage Check         2236
source_sheet                      0
dtype: int64

In [20]:
df.describe(include="all")

,Comments,Lane number,Date,business,senior,family,young,PRM,regular,Experience,...,Time Start WTMD check,Time End WTMD check,Time Start ETD check,Time End ETD check,Time Start Baggage reclaim,Time End Baggage reclaim,Group size,Time Start Baggage Check,Time End Baggage Check,source_sheet
count,1096,2405.000000,2405,444.0,530.0,239.0,372.0,25.0,1067.000000,2403.000000,...,214.000000,213.000000,313.000000,309.000000,2396.0,2396.000000,2402.000000,174.000000,169.000000,2405
unique,697,NaN,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2147.0,NaN,NaN,NaN,NaN,15
top,takes x-ray boxes with him,NaN,2018-12-18 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,51348.0,NaN,NaN,NaN,NaN,2018_12_18a
freq,60,NaN,596,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,321
mean,NaN,2.790437,NaN,1.0,1.0,1.0,1.0,1.0,1.092784,0.609238,...,82921.920561,83084.798122,88082.686901,88523.579288,NaN,86183.851419,2.044963,86522.068966,88544.437870,NaN
std,NaN,0.407082,NaN,0.0,0.0,0.0,0.0,0.0,3.030770,0.488023,...,43809.496440,43875.741022,46025.038119,46169.933409,NaN,44721.320764,1.241907,44879.264245,48871.403953,NaN
min,NaN,2.000000,NaN,1.0,1.0,1.0,1.0,1.0,1.000000,0.000000,...,50244.000000,50255.000000,50000.000000,50227.000000,NaN,50352.000000,1.000000,50252.000000,50259.000000,NaN
25%,NaN,3.000000,NaN,1.0,1.0,1.0,1.0,1.0,1.000000,0.000000,...,54273.250000,54326.000000,54629.000000,54750.000000,NaN,54834.500000,1.000000,54771.250000,55127.000000,NaN
50%,NaN,3.000000,NaN,1.0,1.0,1.0,1.0,1.0,1.000000,1.000000,...,61234.000000,61338.000000,62210.000000,62240.000000,NaN,61958.000000,2.000000,62519.000000,63146.000000,NaN
75%,NaN,3.000000,NaN,1.0,1.0,1.0,1.0,1.0,1.000000,1.000000,...,90939.500000,93434.000000,144117.000000,144221.000000,NaN,141561.250000,2.000000,138867.500000,143424.000000,NaN
max,NaN,3.000000,NaN,1.0,1.0,1.0,1.0,1.0,100.000000,1.000000,...,183228.000000,183244.000000,183417.000000,183422.000000,NaN,184310.000000,10.000000,181228.000000,343154.000000,NaN

In [21]:
for col in df.columns:
    print(col)

Comments
Lane number
Date
business
senior
family
young
PRM
regular
Experience
Time Start Baggage drop off
Number of boxes
Time End Baggage drop off
Time Start WTMD
Time Start WTMD 2
Time Start WTMD 3
Time Start WTMD check
Time End WTMD check
Time Start ETD check
Time End ETD check
Time Start Baggage reclaim
Time End Baggage reclaim
Group size
Time Start Baggage Check
Time End Baggage Check
source_sheet

Here we check all of the different excel sheets to see if the column names match exactly or if there are any mistakes in the namings.

In [22]:
for name, sheet in all_sheets.items():
    print(f"\n{name}")
    print(sheet.columns.tolist())

2018_02_23
['Comments', 'Lane number', 'Date', 'business', 'senior', 'family', 'young', 'PRM', 'regular', 'Experience', 'Time Start Baggage drop off', 'Number of boxes', 'Time End Baggage drop off', 'Time Start WTMD', 'Time Start WTMD 2', 'Time Start WTMD 3', 'Time Start WTMD check', 'Time End WTMD check', 'Time Start ETD check', 'Time End ETD check', 'Time Start Baggage reclaim', 'Time End Baggage reclaim', 'Group size', 'Time Start Baggage Check', 'Time End Baggage Check', 'source_sheet']

2018_03_01
['Comments', 'Lane number', 'Date', 'business', 'senior', 'family', 'young', 'PRM', 'regular', 'Experience', 'Time Start Baggage drop off', 'Number of boxes', 'Time End Baggage drop off', 'Time Start WTMD', 'Time Start WTMD 2', 'Time Start WTMD 3', 'Time Start WTMD check', 'Time End WTMD check', 'Time Start ETD check', 'Time End ETD check', 'Time Start Baggage reclaim', 'Time End Baggage reclaim', 'Group size', 'Time Start Baggage Check', 'Time End Baggage Check', 'source_sheet']

2018_03_10
['Comments', 'Lane number', 'Date', 'business', 'senior', 'family', 'young', 'PRM', 'regular', 'Experience', 'Time Start Baggage drop off', 'Number of boxes', 'Time End Baggage drop off', 'Time Start WTMD', 'Time Start WTMD 2', 'Time Start WTMD 3', 'Time Start WTMD check', 'Time End WTMD check', 'Time Start ETD check', 'Time End ETD check', 'Time Start Baggage reclaim', 'Time End Baggage reclaim', 'Group size', 'Time Start Baggage Check', 'Time End Baggage Check', 'source_sheet']

2018_03_12
['Comments', 'Lane number', 'Date', 'business', 'senior', 'family', 'young', 'PRM', 'regular', 'Experience', 'Time Start Baggage drop off', 'Number of boxes', 'Time End Baggage drop off', 'Time Start WTMD', 'Time Start WTMD 2', 'Time Start WTMD 3', 'Time Start WTMD check', 'Time End WTMD check', 'Time Start ETD check', 'Time End ETD check', 'Time Start Baggage reclaim', 'Time End Baggage reclaim', 'Group size', 'Time Start Baggage Check', 'Time End Baggage Check', 'source_sheet']

2018_03_31
['Comments', 'Lane number', 'Date', 'business', 'senior', 'family', 'young', 'PRM', 'regular', 'Experience', 'Time Start Baggage drop off', 'Number of boxes', 'Time End Baggage drop off', 'Time Start WTMD', 'Time Start WTMD 2', 'Time Start WTMD 3', 'Time Start WTMD check', 'Time End WTMD check', 'Time Start ETD check', 'Time End ETD check', 'Time Start Baggage reclaim', 'Time End Baggage reclaim', 'Group size', 'Time Start Baggage Check', 'Time End Baggage Check', 'source_sheet']

2018_04_07
['Comments', 'Lane number', 'Date', 'business', 'senior', 'family', 'young', 'PRM', 'regular', 'Experience', 'Time Start Baggage drop off', 'Number of boxes', 'Time End Baggage drop off', 'Time Start WTMD', 'Time Start WTMD 2', 'Time Start WTMD 3', 'Time Start WTMD check', 'Time End WTMD check', 'Time Start ETD check', 'Time End ETD check', 'Time Start Baggage reclaim', 'Time End Baggage reclaim', 'Group size', 'Time Start Baggage Check', 'Time End Baggage Check', 'source_sheet']

2018_04_15
['Comments', 'Lane number', 'Date', 'business', 'senior', 'family', 'young', 'PRM', 'regular', 'Experience', 'Time Start Baggage drop off', 'Number of boxes', 'Time End Baggage drop off', 'Time Start WTMD', 'Time Start WTMD 2', 'Time Start WTMD 3', 'Time Start WTMD check', 'Time End WTMD check', 'Time Start ETD check', 'Time End ETD check', 'Time Start Baggage reclaim', 'Time End Baggage reclaim', 'Group size', 'Time Start Baggage Check', 'Time End Baggage Check', 'source_sheet']

2018_04_17a
['Comments', 'Lane number', 'Date', 'business', 'senior', 'family', 'young', 'PRM', 'regular', 'Experience', 'Time Start Baggage drop off', 'Number of boxes', 'Time End Baggage drop off', 'Time Start WTMD', 'Time Start WTMD 2', 'Time Start WTMD 3', 'Time Start WTMD check', 'Time End WTMD check', 'Time Start ETD check', 'Time End ETD check', 'Time Start Baggage reclaim', 'Time End Baggage reclaim', 'Group size', 'Time Start Baggage Check', 'Time End Baggage Check', 'source_sheet']

2018_04_17b
['Comments', 'Lane number', 'Date', 'business', 'senior', 'family', 'young', 'PRM', 'regular', 'Experience', 'Time Start Baggage drop off', 'Number of boxes', 'Time End Baggage drop off', 'Time Start WTMD', 'Time Start WTMD 2', 'Time Start WTMD 3', 'Time Start WTMD check', 'Time End WTMD check', 'Time Start ETD check', 'Time End ETD check', 'Time Start Baggage reclaim', 'Time End Baggage reclaim', 'Group size', 'Time Start Baggage Check', 'Time End Baggage Check', 'source_sheet']

2018_12_06a
['Comments', 'Lane number', 'Date', 'business', 'senior', 'family', 'young', 'PRM', 'regular', 'Experience', 'Time Start Baggage drop off', 'Number of boxes', 'Time End Baggage drop off', 'Time Start WTMD', 'Time Start WTMD 2', 'Time Start WTMD 3', 'Time Start WTMD check', 'Time End WTMD check', 'Time Start ETD check', 'Time End ETD check', 'Time Start Baggage reclaim', 'Time End Baggage reclaim', 'Group size', 'Time Start Baggage Check', 'Time End Baggage Check', 'source_sheet']

2018_12_06b
['Comments', 'Lane number', 'Date', 'business', 'senior', 'family', 'young', 'PRM', 'regular', 'Experience', 'Time Start Baggage drop off', 'Number of boxes', 'Time End Baggage drop off', 'Time Start WTMD', 'Time Start WTMD 2', 'Time Start WTMD 3', 'Time Start WTMD check', 'Time End WTMD check', 'Time Start ETD check', 'Time End ETD check', 'Time Start Baggage reclaim', 'Time End Baggage reclaim', 'Group size', 'Time Start Baggage Check', 'Time End Baggage Check', 'source_sheet']

2018_12_17a
['Comments', 'Lane number', 'Date', 'business', 'senior', 'family', 'young', 'PRM', 'regular', 'Experience', 'Time Start Baggage drop off', 'Number of boxes', 'Time End Baggage drop off', 'Time Start WTMD', 'Time Start WTMD 2', 'Time Start WTMD 3', 'Time Start WTMD check', 'Time End WTMD check', 'Time Start ETD check', 'Time End ETD check', 'Time Start Baggage reclaim', 'Time End Baggage reclaim', 'Group size', 'Time Start Baggage Check', 'Time End Baggage Check', 'source_sheet']

2018_12_17b
['Comments', 'Lane number', 'Date', 'business', 'senior', 'family', 'young', 'PRM', 'regular', 'Experience', 'Time Start Baggage drop off', 'Number of boxes', 'Time End Baggage drop off', 'Time Start WTMD', 'Time Start WTMD 2', 'Time Start WTMD 3', 'Time Start WTMD check', 'Time End WTMD check', 'Time Start ETD check', 'Time End ETD check', 'Time Start Baggage reclaim', 'Time End Baggage reclaim', 'Group size', 'Time Start Baggage Check', 'Time End Baggage Check', 'source_sheet']

2018_12_18a
['Comments', 'Lane number', 'Date', 'business', 'senior', 'family', 'young', 'PRM', 'regular', 'Experience', 'Time Start Baggage drop off', 'Number of boxes', 'Time End Baggage drop off', 'Time Start WTMD', 'Time Start WTMD 2', 'Time Start WTMD 3', 'Time Start WTMD check', 'Time End WTMD check', 'Time Start ETD check', 'Time End ETD check', 'Time Start Baggage reclaim', 'Time End Baggage reclaim', 'Group size', 'Time Start Baggage Check', 'Time End Baggage Check', 'source_sheet']

2018_12_18b
['Comments', 'Lane number', 'Date', 'business', 'senior', 'family', 'young', 'PRM', 'regular', 'Experience', 'Time Start Baggage drop off', 'Number of boxes', 'Time End Baggage drop off', 'Time Start WTMD', 'Time Start WTMD 2', 'Time Start WTMD 3', 'Time Start WTMD check', 'Time End WTMD check', 'Time Start ETD check', 'Time End ETD check', 'Time Start Baggage reclaim', 'Time End Baggage reclaim', 'Group size', 'Time Start Baggage Check', 'Time End Baggage Check', 'source_sheet']